---
- name: "create main dhcp config file"
  template:
    backup: "no"
    dest: "{{DHCP_SYSTEM_PATH}}/{{DHCP_FILE_NAME}}"
    src: "dhcpd_conf_header.j2"
    #validate: /usr/sbin/dhcpd -cf %s
   
- name: "create subnets dhcp config file"
  template:
    backup: "no"
    dest: "{{DHCP_SYSTEM_PATH}}/{{item.1.name}}.conf"
    src: "dhcpd_conf_footer.j2"
  loop: "{{ Network.group|subelements('subnets') }}"
  loop_control:
    label:
      - "{{ item.0.name }}"
      - "{{ item.1.name }}"
  when: item.1.active