---
- name: Start service dhcpd, if not started
  service:
    name: dhcpd
    enabled: yes
    state: started

- name: enable and start firewalld
  service: 
    name: firewalld
    enabled: yes
    state: started


- name: allow dhcp in firewalld
  firewalld:
    service: dhcp
    permanent: yes
    state: enabled
#    immediate: yes
