---
- name: deploy fresh dhcp master and slave instances
  gather_facts: true
  hosts: infra_service_dhcp
  become: true
  roles:
    - init
    - dhcpd-multi-config
    - node_exporter
  strategy: free
