---
- name: deploy fresh dhcp master and slave instances
  gather_facts: true
  hosts:
    - infra_service_dhcp_vis
    - infra_service_dhcp_mir
    - infra_service_dhcp_k12
  become: true
  roles:
    - dhcpd-multi-config
  strategy: linear
