---
all:
  children:
    infra:
      children:
        infra_services:
          children:
            infra_service_dhcp:
              children:
                DHCP_VV_12:
                  hosts:
                    master_vv12:
                      ansible_ssh_host: 192.168.10.155
                    slave_vv12:
                      ansible_ssh_host: 192.168.213.155
                DHCP_MIRAN2:
                  hosts:
                    master_MIRAN2:
                      ansible_ssh_host: 10.98.0.1
                    slave_MIRAN2:
                      ansible_ssh_host: 10.98.2.1
                DHCP_K12:
                  hosts:
                    master_K12:
                      ansible_ssh_host: 10.178.0.1
                    slave_K12:
                      ansible_ssh_host: 10.178.3.1
