---
all:
  children:
    infra:
      children:
        infra_services:
          children:
            infra_service_dhcp:
              children:
                DHCP_VV_12:
                  hosts:
                    master_vv12:
                      ansible_ssh_host: 192.168.10.155
                      ansible_ssh_port: 22
                      INV_VAR_SECONDARY_HOST: 192.168.213.155  # must match slave ip-address
                      INV_VAR_MCLT: "mclt 3600;"
                      INV_VAR_HOST_STATUS: "primary;"
                      INV_VAR_HOST_LOAD_BALANCE_SPLIT: "split 128;"
                      INV_VAR_HOST_LOAD_BALANCE: "load balance max seconds 3;"
                    slave_vv12:
                      ansible_ssh_host: 192.168.213.155
                      ansible_ssh_port: 22
                      INV_VAR_SECONDARY_HOST: 192.168.10.155  # must match master ip-address
                      INV_VAR_MCLT: ""
                      INV_VAR_HOST_STATUS: "secondary;"
                      INV_VAR_HOST_LOAD_BALANCE: ""
                      INV_VAR_HOST_LOAD_BALANCE_SPLIT: ""
                DHCP_MIRAN2:
                  hosts:
                    master_MIRAN2:
                      ansible_ssh_host: 10.98.0.1
                      ansible_ssh_port: 22
                      INV_VAR_SECONDARY_HOST: 10.98.2.1  # must match slave ip-address
                      INV_VAR_MCLT: "mclt 3600;"
                      INV_VAR_HOST_STATUS: "primary;"
                      INV_VAR_HOST_LOAD_BALANCE_SPLIT: "split 128;"
                      INV_VAR_HOST_LOAD_BALANCE: "load balance max seconds 3;"
                    slave_MIRAN2:
                      ansible_ssh_host: 10.98.2.1
                      ansible_ssh_port: 22
                      INV_VAR_SECONDARY_HOST: 10.98.0.1  # must match master ip-address
                      INV_VAR_MCLT: ""
                      INV_VAR_HOST_STATUS: "secondary;"
                      INV_VAR_HOST_LOAD_BALANCE: ""
                      INV_VAR_HOST_LOAD_BALANCE_SPLIT: ""
