---
all:
  children:
    infra:
      children:
        infra_services:
          children:
            infra_service_dhcp:
              children:
                infra_service_dhcp_vis:
                  hosts:
                    sys-net-dhp301.tech.petcorp.ru:
                    sys-net-dhp302.tech.petcorp.ru:
                infra_service_dhcp_mir:
                  hosts:
                    sys-net-dhp101.tech.petcorp.ru:
                    sys-net-dhp102.tech.petcorp.ru:
                infra_service_dhcp_k12:
                  hosts:
                    sys-net-dhp201.tech.petcorp.ru:
                    sys-net-dhp202.tech.petcorp.ru:
