---
- name: Start service dhcpd, if not started
  service:
    name: dhcpd
    enabled: false
    state: stopped

- name: enable and start firewalld
  service:
    name: firewalld
    enabled: true
    state: started


- name: allow dhcp in firewalld
  firewalld:
    service: dhcp
    permanent: true
    state: enabled
#    immediate: yes
