DHCP_hosts:
  hosts:
    host1:
      ansible_ssh_host: 192.168.9.99
      ansible_ssh_port: 22
      ansible_ssh_user: root
#      ansible_ssh_pass: PetR00t
    host2:
      ansible_ssh_host: 192.168.9.199
      ansible_ssh_port: 22
      ansible_ssh_user: root
#      ansible_ssh_pass: PetR00t
