---
- name: "install packages"
  yum:
    name:
      - epel-release
      - bash-completion
      - atop
      - htop
      - iftop
      - firewalld
      - dhcp
      - nano
      - tmux
      - bind-utils
    state: latest
    update_cache: true
