---
- name: "install epel-release"
  yum:
    name:
      - epel-release
    state: latest
    update_cache: true
  tags: cold_start

- name: "install packages"
  yum:
    name:
      - bash-completion
      - net-tools
      - atop
      - htop
      - iftop
      - firewalld
      - dhcp
      - nano
      - tmux
      - bind-utils
      - dhcpd-pools
      - nscd
    state: latest
    update_cache: true
  tags: cold_start
