---
- name: "remove disabled subnets files"
  file:
    dest: "{{DHCP_SUBNET_CONF_PATH}}/{{item.1.name}}.conf"
    state: absent
  loop: "{{ Network.group|subelements('subnets') }}"
  loop_control:
    label:
      - "{{ item.0.name }}"
      - "{{ item.1.name }}"
  when: not item.1.active
  tags:
    - refresh_config
    - cold_start

- name: "create directory for subnet conf files"
  file:
    path: "{{ DHCP_SUBNET_CONF_PATH }}"
    state: directory
    owner: dhcpd
    mode: '0755'
  tags:
    - refresh_config
    - cold_start

- name: "create subnets dhcp config files"
  template:
    dest: "{{ DHCP_SUBNET_CONF_PATH }}/{{item.1.name}}.conf"
    src: "dhcpd_conf_footer.j2"
  loop: "{{ Network.group|subelements('subnets') }}"
  loop_control:
    label:
      - "{{ item.0.name }}"
      - "{{ item.1.name }}"
  when: item.1.active
  tags:
    - refresh_config
    - cold_start

- name: "create main dhcp config file"
  template:
    dest: "{{DHCP_SYSTEM_PATH}}/{{DHCP_FILE_NAME}}"
    src: "dhcpd_conf_header.j2"
    validate: "/usr/sbin/dhcpd -t -cf %s"
  tags:
    - refresh_config
    - cold_start

- name: dhcpd-exporter download
  get_url:
    url: "https://github.com/spagno/iscdhcpd_exporter/releases/download/v0.1.6/iscdhcpd_exporter-0.1.6.linux-amd64.tar.gz"
    dest: "/tmp/iscdhcpd_exporter-0.1.6.linux-amd64.tar.gz"
  tags:
    - cold_start

- name: "unarchive dhcpd-exporter"
  unarchive:
    remote_src: true
    src: /tmp/iscdhcpd_exporter-0.1.6.linux-amd64.tar.gz
    dest: /tmp/
  tags:
    - cold_start

- name: "put dhcpd-exporter to its place"
  copy:
    remote_src: true
    src: /tmp/iscdhcpd_exporter-0.1.6.linux-amd64/iscdhcpd_exporter
    dest: /usr/local/bin/iscdhcpd_exporter
    owner: root
    group: root
    mode: 0755
  tags:
    - cold_start

- name: "dhcpd-exporter systemd unit-file"
  template:
    src: dhcpd_exporter.service.j2
    dest: /etc/systemd/system/dhcpd_exporter.service
  notify: dhcpd_exporter restart
  tags:
    - exporter
