---
- name: "disable selinux"
  selinux:
    policy: targeted
    state: permissive

- name: allow dhcp peer port in firewalld
  firewalld:
    port: "{{ DHCP_PEER_PORT }}/tcp"
    permanent: true
    state: enabled

- name: allow dhcp in firewalld
  firewalld:
    service: dhcp
    permanent: true
    state: enabled

- name: Start services, if not started
  service:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
    state: "{{ item.state }}"
  loop:
    - {name: 'dhcpd', enabled: "true", state: "started"}
    - {name: 'firewalld', enabled: "true", state: "started"}
  loop_control:
    label:
      - "{{ item }}"

- name: "alter owner user:group of /var/lib/dhcpd"
  file:
    path: /var/lib/dhcpd/dhcpd.leases  # may be reverted to root in some ocasions
    owner: dhcpd
    group: dhcpd
    mode: '0644'
