---
Network:
  group:
    - name: "Subnets_REZON"
      subnets:
        - name: "vlan20-IPMI"
          description: "OPS-2862"
          active: true
          guest: false
          bootp: false
          bootp_filename: "{{ VAR_BOOTP_FILENAME }}"
          bootp_server_name: "{{ VAR_BOOTP_SERVER_NAME }}"
          option_ntp_server: "{{ VAR_OPTION_NTP_SERVER }}"
          subnet: 10.78.1.0
          option_routers: 10.78.1.254
          pool_range_start: 10.78.1.150
          pool_range_end: 10.78.1.200
          static: "none"
        - name: "vlan30-physical-and-baremetal"
          description: "OPS-2862"
          active: true
          guest: false
          bootp: false
          bootp_filename: "{{ VAR_BOOTP_FILENAME }}"
          bootp_server_name: "{{ VAR_BOOTP_SERVER_NAME }}"
          option_ntp_server: "{{ VAR_OPTION_NTP_SERVER }}"
          subnet: 10.78.2.0
          option_routers: 10.78.2.254
          pool_range_start: 10.78.2.150
          pool_range_end: 10.78.2.200
          static: "none"
        - name: "network-vlan33-INFRA-services"
          description: "OPS-2554"
          active: true
          guest: false
          bootp: false
          bootp_filename: "{{ VAR_BOOTP_FILENAME }}"
          bootp_server_name: "{{ VAR_BOOTP_SERVER_NAME }}"
          option_ntp_server: "{{ VAR_OPTION_NTP_SERVER }}"
          subnet: 10.78.3.0
          option_routers: 10.78.3.254
          pool_range_start: 10.78.3.150
          pool_range_end: 10.78.3.200
          static:
            - name: "sys-adm-run301.tech"
              mac: "00:50:56:95:cf:09"
              ip: "10.78.3.151"
        - name: "network-vlan34-INFRA-services-2"
          description: "OPS-2554"
          active: true
          guest: false
          bootp: false
          bootp_filename: "{{ VAR_BOOTP_FILENAME }}"
          bootp_server_name: "{{ VAR_BOOTP_SERVER_NAME }}"
          option_ntp_server: "{{ VAR_OPTION_NTP_SERVER }}"
          subnet: 10.78.4.0
          option_routers: 10.78.4.254
          pool_range_start: 10.78.4.150
          pool_range_end: 10.78.4.200
          static: "none"
        - name: "network-vlan50-CRM1"
          description: "OPS-2597"
          active: true
          guest: false
          bootp: false
          bootp_filename: "{{ VAR_BOOTP_FILENAME }}"
          bootp_server_name: "{{ VAR_BOOTP_SERVER_NAME }}"
          option_ntp_server: "{{ VAR_OPTION_NTP_SERVER }}"
          subnet: 10.78.8.0
          option_routers: 10.78.8.254
          pool_range_start: 10.78.8.150
          pool_range_end: 10.78.8.200
          static: "none"
        - name: "network-vlan90-WEB1"
          description: "OPS-2653"
          active: true
          guest: false
          bootp: false
          bootp_filename: "{{ VAR_BOOTP_FILENAME }}"
          bootp_server_name: "{{ VAR_BOOTP_SERVER_NAME }}"
          option_ntp_server: "{{ VAR_OPTION_NTP_SERVER }}"
          subnet: 10.78.100.0
          option_routers: 10.78.100.254
          pool_range_start: 10.78.100.150
          pool_range_end: 10.78.100.200
          static: "none"
        - name: "network-vlan100-WEB2"
          description: "OPS-2653"
          active: true
          guest: false
          bootp: false
          bootp_filename: "{{ VAR_BOOTP_FILENAME }}"
          bootp_server_name: "{{ VAR_BOOTP_SERVER_NAME }}"
          option_ntp_server: "{{ VAR_OPTION_NTP_SERVER }}"
          subnet: 10.78.101.0
          option_routers: 10.78.101.254
          pool_range_start: 10.78.101.150
          pool_range_end: 10.78.101.200
          static: "none"
        - name: "network-40-offices"
          description: "initial"
          active: true
          guest: false
          bootp: false
          bootp_filename: "{{ VAR_BOOTP_FILENAME }}"
          bootp_server_name: "{{ VAR_BOOTP_SERVER_NAME }}"
          option_ntp_server: "{{ VAR_OPTION_NTP_SERVER }}"
          subnet: 192.168.40.0
          option_routers: 192.168.40.254
          pool_range_start: 192.168.40.40
          pool_range_end: 192.168.40.230
          static:
            - name: "static-Irina.Perova"  # NQY-44305 helpdesk
              mac: "9C:5C:8E:7B:6C:05"
              ip: "192.168.40.222"
            - name: "static-Alena.Vasilevich"  # WSK-08185 helpdesk
              mac: "04:92:26:C4:D6:DE"
              ip: "192.168.40.91"
            - name: "static-Olga.Kuchevasova"  # HHX-56427 helpdesk
              mac: "40:B0:76:DC:81:88"
              ip: "192.168.40.96"
        - name: "network-41-offices"
          description: "initial"
          active: true
          guest: false
          bootp: false
          bootp_filename: "{{ VAR_BOOTP_FILENAME }}"
          bootp_server_name: "{{ VAR_BOOTP_SERVER_NAME }}"
          option_ntp_server: "{{ VAR_OPTION_NTP_SERVER }}"
          subnet: 192.168.41.0
          option_routers: 192.168.41.254
          pool_range_start: 192.168.41.40
          pool_range_end: 192.168.41.230
          static:
            - name: "static-Lubov.Pavlova"  # JXS-96760 helpdesk
              mac: "BC:5F:F4:CE:F3:5B"
              ip: "192.168.41.49"
        - name: "network-200-wifi"
          description: "initial"
          active: true
          guest: false
          bootp: false
          bootp_filename: "{{ VAR_BOOTP_FILENAME }}"
          bootp_server_name: "{{ VAR_BOOTP_SERVER_NAME }}"
          option_ntp_server: "{{ VAR_OPTION_NTP_SERVER }}"
          subnet: 192.168.200.0
          option_routers: 192.168.200.254
          pool_range_start: 192.168.200.50
          pool_range_end: 192.168.200.200
          static: "none"
        - name: "network-201-wifi-guests"
          description: "initial"
          active: true
          guest: true
          bootp: false
          bootp_filename: "{{ VAR_BOOTP_FILENAME }}"
          bootp_server_name: "{{ VAR_BOOTP_SERVER_NAME }}"
          option_ntp_server: "{{ VAR_OPTION_NTP_SERVER }}"
          subnet: 192.168.201.0
          option_routers: 192.168.201.254
          pool_range_start: 192.168.201.50
          pool_range_end: 192.168.201.200
          static: "none"
        - name: "network-213-IT-Dept"
          description: "initial"
          active: true
          guest: false
          bootp: false
          bootp_filename: "{{ VAR_BOOTP_FILENAME }}"
          bootp_server_name: "{{ VAR_BOOTP_SERVER_NAME }}"
          option_ntp_server: "{{ VAR_OPTION_NTP_SERVER }}"
          subnet: 192.168.213.0
          option_routers: 192.168.213.254
          pool_range_start: 192.168.213.51
          pool_range_end: 192.168.213.100
          static:
            - name: "sys-stg-bkp002.bmc"
              mac: "00:1e:67:14:d0:d2"
              ip: "192.168.213.59"
            - name: "srv-vis024.bmc"
              mac: "6c:ae:8b:41:7a:de"
              ip: "192.168.213.39"
            - name: "srv-vis021.bmc"
              mac: "ac:1f:6b:ae:62:0c"
              ip: "192.168.213.96"
            - name: "192.168.213.35-BMC"
              mac: "6c:ae:8b:41:7a:46"
              ip: "192.168.213.33"
            - name: "srv-vis022.tech"
              mac: "3C:7C:3F:BC:6B:20"
              ip: "192.168.213.79"
            - name: "srv-vis023.tech"
              mac: "3C:7C:3F:BC:6A:6F"
              ip: "192.168.213.54"
            - name: "dev-web-srv011.tech"
              mac: "18:c0:4d:89:a2:31"
              ip: "192.168.213.56"
            - name: "sys-adm-blx301.tech"
              mac: "00:50:56:95:ab:54"
              ip: "192.168.213.99"
            - name: "tst-ops-pql301.tech"
              mac: "00:50:56:95:25:34"
              ip: "192.168.213.64"
        - name: "network-7-vlan307-ROZNITSA"
          description: "OPS-2294"
          active: true
          guest: false
          bootp: false
          bootp_filename: "{{ VAR_BOOTP_FILENAME }}"
          bootp_server_name: "{{ VAR_BOOTP_SERVER_NAME }}"
          option_ntp_server: "{{ VAR_OPTION_NTP_SERVER }}"
          subnet: 192.168.7.0
          option_routers: 192.168.7.254
          pool_range_start: 192.168.7.100
          pool_range_end: 192.168.7.200
          static: "none"
        - name: "network-10-vlan310-Networking"
          description: "initial"
          active: true
          guest: false
          bootp: true
          bootp_filename: "{{ VAR_BOOTP_FILENAME }}"
          bootp_server_name: "{{ VAR_BOOTP_SERVER_NAME }}"
          option_ntp_server: "{{ VAR_OPTION_NTP_SERVER }}"
          subnet: 192.168.10.0
          option_routers: 192.168.10.254
          pool_range_start: 192.168.10.150
          pool_range_end: 192.168.10.200
          static: "none"
    - name: "Subnets_DEV-OFFICE"
      subnets:
        - name: "network-221-dev-office-JAVA-AND-CRM"
          description: "OPS-2257"
          active: true
          guest: false
          bootp: true
          bootp_filename: "{{ VAR_BOOTP_FILENAME }}"
          bootp_server_name: "{{ VAR_BOOTP_SERVER_NAME }}"
          option_ntp_server: "{{ VAR_OPTION_NTP_SERVER }}"
          subnet: 192.168.221.0
          option_routers: 192.168.221.1
          pool_range_start: 192.168.221.10
          pool_range_end: 192.168.221.250
          static:
            - name: "dev-jav-clk301.tech"
              mac: "00:50:56:9A:C3:55"
              ip: "192.168.221.140"
            - name: "dev-crm-zoo002.tech"
              mac: "00:0C:29:A8:D4:13"
              ip: "192.168.221.174"
            - name: "tst-jav-kfk001.tech"
              mac: "00:0C:29:5B:FB:6F"
              ip: "192.168.221.175"
            - name: "dev-crm-zoo001.tech"
              mac: "00:0C:29:E1:DA:C5"
              ip: "192.168.221.176"
            - name: "dev-web-srv008.tech"
              mac: "00:15:17:D0:FB:2D"
              ip: "192.168.221.197"
            - name: "prn-web-dpt"
              mac: "30:E1:71:3F:34:66"
              ip: "192.168.221.230"
            - name: "srv-chk001.bmc"
              mac: "b4:b5:2f:68:21:c0"
              ip: "192.168.221.5"
            - name: "192.168.221.135-a.gorbachev-desktop"
              mac: "d4:5d:64:3a:f2:a1"
              ip: "192.168.221.135"
            - name: "tst-ops-clk301.tech"
              mac: "00:50:56:95:c8:21"
              ip: "192.168.221.18"
        - name: "network-88-dev-office-CHEF-AND-SWITCH"
          description: "OPS-2257"
          active: true
          guest: false
          bootp: true
          bootp_filename: "{{ VAR_BOOTP_FILENAME }}"
          bootp_server_name: "{{ VAR_BOOTP_SERVER_NAME }}"
          option_ntp_server: "{{ VAR_OPTION_NTP_SERVER }}"
          subnet: 192.168.88.0
          option_routers: 192.168.88.1
          pool_range_start: 192.168.88.10
          pool_range_end: 192.168.88.240
          static: "none"
        - name: "network-33-dev-office-test-stand"
          description: "OPS-2257"
          active: true
          guest: false
          bootp: true
          bootp_filename: "{{ VAR_BOOTP_FILENAME }}"
          bootp_server_name: "{{ VAR_BOOTP_SERVER_NAME }}"
          option_ntp_server: "{{ VAR_OPTION_NTP_SERVER }}"
          subnet: 192.168.33.0
          option_routers: 192.168.33.1
          pool_range_start: 192.168.33.10
          pool_range_end: 192.168.33.250
          static: "none"
        - name: "network-30-dev-office-designers"
          description: "OPS-2257"
          active: true
          guest: false
          bootp: true
          bootp_filename: "{{ VAR_BOOTP_FILENAME }}"
          bootp_server_name: "{{ VAR_BOOTP_SERVER_NAME }}"
          option_ntp_server: "{{ VAR_OPTION_NTP_SERVER }}"
          subnet: 192.168.30.0
          option_routers: 192.168.30.1
          pool_range_start: 192.168.30.10
          pool_range_end: 192.168.30.250
          static:
            - name: "Disigners-printer"
              mac: "10:62:E5:AC:89:36"
              ip: "192.168.30.20"
        - name: "network-35-dev-office-wifi"
          description: "OPS-2099"
          active: true
          guest: false
          bootp: false
          bootp_filename: "{{ VAR_BOOTP_FILENAME }}"
          bootp_server_name: "{{ VAR_BOOTP_SERVER_NAME }}"
          option_ntp_server: "{{ VAR_OPTION_NTP_SERVER }}"
          subnet: 192.168.35.0
          option_routers: 192.168.35.1
          pool_range_start: 192.168.35.20
          pool_range_end: 192.168.35.250
          static:
            - name: "wifi-spot-java"
              mac: "14:EB:B6:EC:DE:D8"
              ip: "192.168.35.39"
            - name: "wifi-spot-peregovorka"
              mac: "0c:80:63:07:1b:f2"
              ip: "192.168.35.41"
            - name: "wifi-spot-inzineri"
              mac: "0c:80:63:07:1B:44"
              ip: "192.168.35.42"
            - name: "wifi-spot-vhod-stolovaya"
              mac: "0c:80:63:07:04:6c"
              ip: "192.168.35.43"
            - name: "wifi-spot-vhod-prods-peregovorka"
              mac: "50:D4:F7:77:94:94"
              ip: "192.168.35.44"
            - name: "wifi-spot-vhod-prods-u-okna"
              mac: "50:d4:F7:77:94:cA"
              ip: "192.168.35.45"
        - name: "network-80-dev-office-guest-wifi"
          description: "OPS-2099"
          active: true
          guest: true
          bootp: false
          bootp_filename: "{{ VAR_BOOTP_FILENAME }}"
          bootp_server_name: "{{ VAR_BOOTP_SERVER_NAME }}"
          option_ntp_server: "{{ VAR_OPTION_NTP_SERVER }}"
          subnet: 192.168.80.0
          option_routers: 192.168.80.1
          pool_range_start: 192.168.80.100
          pool_range_end: 192.168.80.200
          static: "none"
        - name: "network-25-dev-office"
          description: "ingineers"
          active: true
          guest: false
          bootp: true
          bootp_filename: "{{ VAR_BOOTP_FILENAME }}"
          bootp_server_name: "{{ VAR_BOOTP_SERVER_NAME }}"
          option_ntp_server: "{{ VAR_OPTION_NTP_SERVER }}"
          subnet: 192.168.25.0
          option_routers: 192.168.25.1
          pool_range_start: 192.168.25.10
          pool_range_end: 192.168.25.100
          static:
            - name: "192.168.25.20-BMC"
              mac: "02:25:90:F4:29:7E"
              ip: "192.168.25.5"
            - name: "srv-chk006.bmc"
              mac: "a4:5d:36:fc:83:92"
              ip: "192.168.25.4"
            - name: "srv-chk002.bmc"
              mac: "80:c1:6e:6d:44:20"
              ip: "192.168.25.17"
            - name: "sys-adm-kvm002.bmc"
              mac: "00:15:17:9e:7c:66"
              ip: "192.168.25.7"
            - name: "s.stepanov-thinkpad"
              mac: "30:E1:71:3F:34:66"
              ip: "192.168.25.150"
            - name: "sys-stg-srv002.bmc"
              mac: "02:25:90:F0:52:26"
              ip: "192.168.25.238"
            - name: "sys-adm-blx302.tech"
              mac: "00:50:56:95:54:8b"
              ip: "192.168.25.82"
            - name: "prd-jav-ent301.tech"
              mac: "00:50:56:95:6f:f0"
              ip: "192.168.25.33"
            - name: "srv-chk005.bmc"
              mac: "6c:3b:e5:b4:14:ea"
              ip: "192.168.25.49"
            - name: "tst-ops-mon301.tech"
              mac: "B6:49:00:61:0E:E9"
              ip: "192.168.25.22"
