---
- name: lookup key
  set_fact:
    keys: "{{ lookup('url', 'https://gitlab.petcorp.ru/{{ item }}.keys', split_lines=false) }}"
  delegate_to: localhost
  run_once: true

- name: added group "{{ item }}"
  group:
    name: "{{ item }}"

- name: added groups for "{{ item }}"
  user:
    name: "{{ item }}"
    groups: "wheel, {{ item }}"
    group: "{{ item }}"
    password: ""
    state: present

- name: added ssh key for "{{ item }}"
  authorized_key:
    user: "{{ item }}"
    state: present
    manage_dir: true
    key: "{{ keys }}"
