---
- name: Copy bashrc
  template:
    src: g.balandin/bashrc.j2
    dest: /home/{{ item }}/.bashrc
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0640
  loop:
    - g.balandin
    - s.stepanov
  tags:
    - tools

- name: install tmux
  yum:
    name:
      - tmux
    state: installed
  tags:
    - tools

- name: Copy tmux
  template:
    src: g.balandin/tmux.conf.j2
    dest: /home/g.balandin/.tmux.conf
    owner: g.balandin
    group: g.balandin
    mode: 0640
  tags:
    - tools

- name: timezone
  timezone:
    name: Europe/Moscow
