---
- name: remove dhcpd.conf if exists
  file:
    path: "{{DHCP_SYSTEM_PATH}}/{{DHCP_FILE_NAME}}"
    state: absent
    
- name: "create dhcp config file"
  template:
    backup: "no"
    dest: "{{DHCP_CONF_PATH}}/{{DHCP_FILE_NAME}}"
    src: "/home/alx/git/dhcp/roles/deploy-dhcpd-master/templates/master.j2"

#- name: "create dhcpd config file symlink"
#  file:  
#    src: "{{DHCP_CONF_PATH}}/{{DHCP_FILE_NAME}}"
#    dest: "{{DHCP_SYSTEM_PATH}}/{{DHCP_FILE_NAME}}"
#    owner: root
#    group: root
#    state: link
